# Generated by Django 3.1.2 on 2020-10-29 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=70)),
                ('message', models.CharField(max_length=180, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vitabu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ifuku', models.FileField(upload_to='uploads/')),
                ('ifuku_image', models.ImageField(blank=True, upload_to='uploads/')),
            ],
        ),
    ]
